name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: cli/cli@v2
        with:
          version: latest

      - name: Get version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep -m 1 'version =' "pyproject.toml" | awk -F'"' '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        run: |
          gh release create "${{ env.VERSION }}" --title "${{ env.VERSION }}" --notes "Release ${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
